name = "pastbin"
compatibility_date = "2024-07-28"

[[r2_buckets]]
binding = "R2"
bucket_name = "pastbin"

[[d1_databases]]
binding = "DB"
database_name = "pastbin"
database_id = "20a85d1c-2a20-4e32-bc4c-4856a4f115f5"

[[routes]]
pattern = "kuu.cat"
custom_domain = true

[placement]
mode = "smart"

[vars]
SERVER = "https://kuu.cat/"

FAVICON = "https://ocfox.me/favicon.ico"

KEY_LENGTH = 4
